meta_product_name: "Go!rilla"
meta_title: "Go!rilla - Find your next gym buddy"
meta_description: "Connect with gym Veterans and work out together"
meta_image: "GorillaOGimage.png" # should exist in `app/assets/images/`
